# Generated by Django 3.0.5 on 2020-10-20 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_list",
                to="recipe.Recipe",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
