# Generated by Django 3.0.5 on 2020-10-25 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_recipe",
                to="recipe.Recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="followrecipe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_recipe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="followuser",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор побликации",
            ),
        ),
        migrations.AlterField(
            model_name="followuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="dimension",
            field=models.CharField(max_length=20, verbose_name="Единица измерения"),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор публикации",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(verbose_name="Текстовое описание"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipe/", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipe.RecipeIngre",
                to="recipe.Ingredients",
                verbose_name="Ингридиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(to="recipe.Tags", verbose_name="Тэг"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="time",
            field=models.CharField(max_length=45, verbose_name="Время приготовления"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=45, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="recipeingre",
            name="ingredients",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.Ingredients",
                verbose_name="Ингридиент",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingre",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.Recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_list",
                to="recipe.Recipe",
                verbose_name="Список покупок",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_list",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="title",
            field=models.CharField(
                choices=[
                    ("breakfast", "Завтрак"),
                    ("lunch", "Обед"),
                    ("dinner", "Ужин"),
                ],
                max_length=10,
                verbose_name="Название тэга",
            ),
        ),
    ]
