# Generated by Django 3.0.5 on 2020-10-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20201024_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Ingre',
            new_name='RecipeIngre',
        ),
    ]
