# Generated by Django 3.0.5 on 2020-10-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_auto_20201020_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe_ingre",
            name="count",
            field=models.FloatField(),
        ),
    ]
